### PR TITLE
Added missing info. for Google AMP validation in Search Console

### PR DESCRIPTION
**Pull request by nbdl**
Added publisher info and modifiedDate to the schema for a single post.

### CODE REVIEW

**Comment by nbdl** [comment]
Hello,
We noticed that in the Google Search Console, some errors/warnings were reported with the posts JSON schema.
The validator notified us that it was missing some publisher infos, as well as the modifiedDate.

The error reads "The attribute publisher.itemtype has an incorrect value"
The warning reads "It is preferable to fill the field dateModified. Please give a value if possible."

image

**Comment by nbdl** [comment]
Changed the generation of the canonical URL as well, because of Google Search Console's following message.

amp-content-mismatch

**Comment by Dibbyo456** [comment]
That’s great.. I was hoping when the dev will fix it.

**Comment by Dibbyo456** [comment]
**Update**: I think this is fixed at **v1.7.1**

**Pull request closed without merging**
